dist: trusty
sudo: required
cache: bundler
language: ruby
before_install:
  - gem update --system # https://github.com/travis-ci/travis-ci/issues/8978
  - gem install bundler
script:
  - bundle exec rubocop
  - bundle exec rake
